services:
  - type: web
    name: truxscrapper
    env: docker
    plan: free
    region: oregon  # or ohio if you prefer
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:80
    ports:
      - 80
